# Compile with G++
buildLinux:
    tags:
        - linux
        - console
    stage: build
    script:
        - g++ ./ThreadQueue/test.cpp -o test.out
    artifacts:
        paths:
            - test.out